### ISSUE TITLE
作者您好，就按您这个配置就可以吗

### ISSUE THREAD

**Issue by ni909** [Masaaki-75/proct#2]
![配置单](https://github.com/Masaaki-75/proct/assets/86198274/8421393c-64df-48eb-994c-6268920d16f4)

**Comment by Masaaki-75** [comment]
我们建议您按照本仓库中[inst_tr.sh](https://github.com/Masaaki-75/proct/blob/main/inst_tr.sh)文件或者README文档中的步骤进行安装
