### ISSUE TITLE
关于模型输入需求

### ISSUE THREAD

**Issue by Deliver0** [Masaaki-75/proct#3]
作者您好，请问在使用您的模型进行推理或微调时，是否必须要获取有限角稀疏角CT数据所对应的采样角度信息，以生成正弦掩膜作为模型输入的promote？感谢！

**Comment by Masaaki-75** [comment]
如果您采用的是目前公开的权重，那么是的，确实需要提供采样角度信息。如果您选择重新训练一个，而使用了可学习的prompt，则不需要提供采样角度信息

**Comment by Deliver0** [comment]
非常感谢您的回答！请问您所说的可学习的prompt是需要自行设计和验证吗？

**Comment by Masaaki-75** [comment]
您可以在
https://github.com/Masaaki-75/proct/blob/main/sources/proct.py#L877
中，将参数`use_learnable_prompt`设为True，即可在训练中使用可学习的prompt。该prompt的默认形状为`(1, 2, 5, 720)`，分别表示`dummy batch_size`、`2`种场景（稀疏角度+有限角度）、每种场景大致可分为`5`种难度（见论文补充材料关于learnable prompt的部分）、以及`720`个视角。

**Comment by Deliver0** [comment]
好的，非常感谢！

**Comment by Deliver0** [comment]
您好，根据您的建议prompt可以做到无需手动输入了，但是context似乎仍需要根据CT数据的采样角度信息生成，有没有类似的解决方法呢。我希望将您的模型在没有采样角度信息的稀疏角和有限角CT数据上进行推理和训练。

**Comment by Deliver0** [comment]
您好，根据您的建议prompt可以做到无需手动输入了，但是context似乎仍需要根据CT数据的采样角度信息生成，有没有类似的解决方法呢。我希望将您的模型在没有采样角度信息的稀疏角和有限角CT数据上进行推理和训练。

**Comment by Masaaki-75** [comment]
这是本工作的一个改进方向——在不依赖in-context pair的情况下仍能有效提高模型对复杂伪影的去除性能，本质上是做到无条件的多任务学习，非常欢迎继续研究和交流！

**Comment by Masaaki-75** [comment]
对于本工作而言，您可以尝试直接用输入的原图像替换掉in-context pair。根据前期实验 (Row (4) of Table 3)，性能会有轻微的下降，但仍能实现多任务的统一伪影消除。

**Comment by Deliver0** [comment]
谢谢您的解答！您的建议非常有帮助，我会按您所说的去尝试下，也很期待你们的进一步工作！

**Comment by Deliver0** [comment]
在按您所说的直接用输入的原图像替换掉in-context pair的方法训练模型之后，在推理的时候没有in-context pair的gt，这您是如何解决的呢？

**Comment by Masaaki-75** [comment]
in-coontext是作为输入提供辅助信息的，不需要GT监督。请问可以具体说明一下问题嘛？

**Comment by Deliver0** [comment]
哦那可能是我理解错了。我根据论文中的Fig.2以及easy_demo相关代码理解的是，in-context pair是缺陷图及其GT的图像对。但实际上只需要一个缺陷图作为context吗？

**Comment by Masaaki-75** [comment]
我明白您的意思了。您之前的理解是对的，提供一张缺陷图及其对应的高质量CT图像是最好的。

> 对于本工作而言，您可以尝试直接用输入的原图像替换掉in-context pair。根据前期实验 (Row (4) of Table 3)，性能会有轻微的下降，但仍能实现多任务的统一伪影消除。

我之前提出的这个方案实际上是去除in-context pair的一个消融研究，在实现上就是将上述一对in-context pair直接替换成和输入图像（即复制两份）。在[这行代码](https://github.com/Masaaki-75/proct/blob/main/trainers/proct_trainer.py#L357)中，将`context`替换成`images.unsqueeze(1).repeat(1, support_size, 2, 1, 1)`（即令其形状变为`(batch_size, support_size, 2, H, W)`）即可实现这一方案。

这就相当于不给模型提供任何的in-context信息了，因此会导致性能下降。推理的时候，自然也不需要提供in-context信息，直接把输入图像复制两份送入到contextual branch就好了。

**Comment by Deliver0** [comment]
明白了！ 非常感谢您的耐心解答！
